# Generated by Django 6.0.4 on 2026-04-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_custom_colors_light',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_custom_mode',
            field=models.CharField(blank=True, default='dark', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
