# Generated by Django 6.0.4 on 2026-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_theme_custom_colors_light_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_custom_colors_light',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='theme_custom_mode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(default='dark', max_length=20),
        ),
    ]
