# Generated by Django 6.0.4 on 2026-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_theme_custom_colors_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
