# Generated by Django 6.0.4 on 2026-05-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_last_completed_date_userprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_pomodoro_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pomodoros_today',
            field=models.IntegerField(default=0),
        ),
    ]
