# Generated by Django 6.0.4 on 2026-05-13 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_failed_login_attempts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_ok', 'Login success'), ('login_fail', 'Login failed'), ('register', 'Registered'), ('task_create', 'Task created'), ('task_complete', 'Task completed'), ('task_delete', 'Task deleted'), ('note_create', 'Note created'), ('note_delete', 'Note deleted'), ('cat_create', 'Category created'), ('cat_delete', 'Category deleted'), ('admin_unlock', 'Admin: unlocked'), ('admin_delete', 'Admin: deleted user'), ('admin_award_xp', 'Admin: awarded XP'), ('admin_reset_xp', 'Admin: reset XP'), ('admin_kick', 'Admin: force logout'), ('admin_staff', 'Admin: toggled staff'), ('admin_note_del', 'Admin: deleted note'), ('admin_bulk', 'Admin: bulk action'), ('delete_account', 'Account deleted'), ('level_up', 'Level up')], max_length=40)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
