# Generated by Django 6.0.4 on 2026-05-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_ok', 'Login success'), ('login_fail', 'Login failed'), ('register', 'Registered'), ('task_create', 'Task created'), ('task_complete', 'Task completed'), ('task_delete', 'Task deleted'), ('note_create', 'Note created'), ('note_delete', 'Note deleted'), ('cat_create', 'Category created'), ('cat_delete', 'Category deleted'), ('admin_unlock', 'Admin: unlocked'), ('admin_delete', 'Admin: deleted user'), ('admin_award_xp', 'Admin: awarded XP'), ('admin_reset_xp', 'Admin: reset XP'), ('admin_kick', 'Admin: force logout'), ('admin_staff', 'Admin: toggled staff'), ('admin_note_del', 'Admin: deleted note'), ('admin_bulk', 'Admin: bulk action'), ('delete_account', 'Account deleted'), ('level_up', 'Level up'), ('admin_view_user', 'Admin: viewed user data'), ('admin_view_note', 'Admin: read note content')], max_length=40),
        ),
    ]
