# Generated by Django 6.0.4 on 2026-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
