# Generated by Django 6.0.4 on 2026-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auditlog_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='is_guest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
