# Generated by Django 6.0.4 on 2026-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_category_icon_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynotes',
            name='color',
            field=models.CharField(default='#7c6aff', max_length=20),
        ),
    ]
