# Generated by Django 6.0.4 on 2026-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
