# Generated by Django 6.0.4 on 2026-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stickynotes',
            name='is_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
