# Generated by Django 6.0.4 on 2026-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='recurrence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
