# Generated by Django 6.0.4 on 2026-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
