# Generated by Django 6.0.4 on 2026-06-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='wip',
            field=models.BooleanField(default=False),
        ),
    ]
